### ISSUE TITLE
IELE

### ISSUE THREAD

**Issue by hellc** [input-output-hk/mantis#469]
First of all: "IELE Tesnet Release v0.1" is not a good name for million of developers. If it is possible pls update it to "Tes**t**net".

Also I couldn't start mantis due the:
```
Ivans-MacBook-Pro:mantis-1.0-daedalus-rc1 ivanmanov$ ./bin/mantis 
21:37:14 Slf4jLogger started
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'environment'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
	at io.iohk.ethereum.metrics.MetricsConfig$.apply(MetricsConfig.scala:38)
	at io.iohk.ethereum.metrics.MetricsClient$.configure(MetricsClient.scala:80)
	at io.iohk.ethereum.nodebuilder.BaseNode.startMetricsClient(StdNode.scala:55)
	at io.iohk.ethereum.nodebuilder.BaseNode.start(StdNode.scala:62)
	at io.iohk.ethereum.Mantis$.main(Mantis.scala:12)
	at io.iohk.ethereum.App$.main(App.scala:23)
	at io.iohk.ethereum.App.main(App.scala)
21:37:24 UDP server not running. Not sending ping message.
21:37:24 UDP server not running. Not sending ping message.
21:37:24 UDP server not running. Not sending ping message.
```

Is that normal? Could you provide some guide to run it properly or fix configuration files...?

**Comment by loverdos** [comment]
@hellc Thanks for bringing `No configuration setting found for key 'environment'` to our attention. It has been [fixed](https://github.com/input-output-hk/mantis/pull/466) and the updated code will make it into the next release.

Also thanks for catching the _tesnet_ typo !
