### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by prographo** [input-output-hk/mantis#483]
Maybe I missed a readme file or something, but how do I run it?

```
ubuntu@ip-172-31-99-99:~/mantis-1.0-daedalus-rc1$ ./bin/mantis -h
Usage:  [options]

  -h | -help         print this message
  -v | -verbose      this runner is chattier
  -d | -debug        set sbt log level to debug
  -no-version-check  Don't run the java version check.
  -main <classname>  Define a custom main class
  -jvm-debug <port>  Turn on JVM debugging, open at the given port.

  # java version (default: java from PATH, currently java version "1.8.0_171")
  -java-home <path>         alternate JAVA_HOME

  # jvm options and output control
  JAVA_OPTS          environment variable, if unset uses ""
  -Dkey=val          pass -Dkey=val directly to the java runtime
  -J-X               pass option -X directly to the java runtime
                     (-J is stripped)

  # special option
  --                 To stop parsing built-in commands from the rest of the command-line.
                     e.g.) enabling debug and sending -d as app argument
                     $ ./start-script -d -- -d

In the case of duplicated or conflicting options, basically the order above
shows precedence: JAVA_OPTS lowest, command line options highest except "--".
ubuntu@ip-172-31-99-99:~/mantis-1.0-daedalus-rc1$ ./bin/mantis 
12:15:57 Slf4jLogger started
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'environment'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
	at io.iohk.ethereum.metrics.MetricsConfig$.apply(MetricsConfig.scala:38)
	at io.iohk.ethereum.metrics.MetricsClient$.configure(MetricsClient.scala:80)
	at io.iohk.ethereum.nodebuilder.BaseNode.startMetricsClient(StdNode.scala:55)
	at io.iohk.ethereum.nodebuilder.BaseNode.start(StdNode.scala:62)
	at io.iohk.ethereum.Mantis$.main(Mantis.scala:12)
	at io.iohk.ethereum.App$.main(App.scala:23)
	at io.iohk.ethereum.App.main(App.scala)
```

**Comment by wang2bo2** [comment]
Check this out https://github.com/input-output-hk/mantis/wiki/Mallet

**Comment by nomelc** [comment]
I tried to access the Cardano KEVM testnet with mantis and mallet and I run into the same error. I followed the instructions in this [medium article](https://medium.com/emurgohk/how-to-get-on-the-cardano-kevm-testnet-835009fa2c8d) and when starting mantis I get the same exception followed by another error when shutting mantis down. The testnet uses atomix-raft consensus but changing /conf/consensus.conf from ethash to atomix-raft does not solve the issue.

System: Ubuntu 16.04
```java version "1.8.0_171"``` 
```IELE Testnet Release v0.1```

```./bin/mantis
14:34:30 Slf4jLogger 
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'environment'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
        at io.iohk.ethereum.metrics.MetricsConfig$.apply(MetricsConfig.scala:38)
        at io.iohk.ethereum.metrics.MetricsClient$.configure(MetricsClient.scala:80)
        at io.iohk.ethereum.nodebuilder.BaseNode.startMetricsClient(StdNode.scala:55)
        at io.iohk.ethereum.nodebuilder.BaseNode.start(StdNode.scala:62)
        at io.iohk.ethereum.Mantis$.main(Mantis.scala:12)
        at io.iohk.ethereum.App$.main(App.scala:23)
        at io.iohk.ethereum.App.main(App.scala)
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
14:34:40 UDP server not running. Not sending ping message.
^C
14:34:43 Using Mantis internal VM
14:34:43 Using 'ethash' consensus [io.iohk.ethereum.consensus.ethash.EthashConsensus]
14:34:43 Error while shutting down...
java.lang.IllegalStateException: cannot create children while terminating or terminated
        at akka.actor.dungeon.Children.makeChild(Children.scala:266)
        at akka.actor.dungeon.Children.attachChild(Children.scala:44)
        at akka.actor.dungeon.Children.attachChild$(Children.scala:43)
        at akka.actor.ActorCell.attachChild(ActorCell.scala:374)
        at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:736)
        at io.iohk.ethereum.nodebuilder.PendingTransactionsManagerBuilder.pendingTransactionsManager(NodeBuilder.scala:257)
        at io.iohk.ethereum.nodebuilder.PendingTransactionsManagerBuilder.pendingTransactionsManager$(NodeBuilder.scala:256)
        at io.iohk.ethereum.nodebuilder.BaseNode.pendingTransactionsManager$lzycompute(StdNode.scala:23)
        at io.iohk.ethereum.nodebuilder.BaseNode.pendingTransactionsManager(StdNode.scala:23)
        at io.iohk.ethereum.nodebuilder.EthServiceBuilder.ethService(NodeBuilder.scala:322)
        at io.iohk.ethereum.nodebuilder.EthServiceBuilder.ethService$(NodeBuilder.scala:321)
        at io.iohk.ethereum.nodebuilder.BaseNode.ethService$lzycompute(StdNode.scala:23)
        at io.iohk.ethereum.nodebuilder.BaseNode.ethService(StdNode.scala:23)
        at io.iohk.ethereum.nodebuilder.JSONRpcControllerBuilder.jsonRpcController(NodeBuilder.scala:359)
        at io.iohk.ethereum.nodebuilder.JSONRpcControllerBuilder.jsonRpcController$(NodeBuilder.scala:359)
        at io.iohk.ethereum.nodebuilder.BaseNode.jsonRpcController$lzycompute(StdNode.scala:23)
        at io.iohk.ethereum.nodebuilder.BaseNode.jsonRpcController(StdNode.scala:23)
        at io.iohk.ethereum.nodebuilder.JSONRpcIpcServerBuilder.jsonRpcIpcServer(NodeBuilder.scala:371)
        at io.iohk.ethereum.nodebuilder.JSONRpcIpcServerBuilder.jsonRpcIpcServer$(NodeBuilder.scala:371)
        at io.iohk.ethereum.nodebuilder.BaseNode.jsonRpcIpcServer$lzycompute(StdNode.scala:23)
        at io.iohk.ethereum.nodebuilder.BaseNode.jsonRpcIpcServer(StdNode.scala:23)
        at io.iohk.ethereum.nodebuilder.BaseNode.$anonfun$shutdown$4(StdNode.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.Try$.apply(Try.scala:209)
        at io.iohk.ethereum.nodebuilder.BaseNode.tryAndLogFailure$1(StdNode.scala:83)
        at io.iohk.ethereum.nodebuilder.BaseNode.shutdown(StdNode.scala:92)
        at io.iohk.ethereum.nodebuilder.ShutdownHookBuilder$$anon$2.run(NodeBuilder.scala:451)
```

When I just run the mallet without starting mantis everything starts but transactions are not carried out and no balances are changing. Therefore, I assume mantis is needed to connect to the Cardano KEVM testnet.

**Comment by nomelc** [comment]
I think, I figured it out. My assumption that mantis is needed was wrong. You only need to run mallet connected to the KEVM net. My transactions failed because my gas and gasPrice parameters were wrong. Here is the complete setup that worked for me to send transactions on the Cardano KEVM testnet with mallet:
```
# install java
> sudo add-apt-repository ppa:webupd8team/java
> sudo apt-get update
> sudo apt-get install oracle-java8-installer
# set path in /etc/environment
JAVA_HOME=”/usr/lib/jvm/java-8-oracle/jre/bin/java”
> source /etc/environment
# download mantis
> wget https://github.com/input-output-hk/mantis/releases/download/iele_testnet_v0.1/mantis_iele-testnet_v0.1.zip
> unzip mantis_iele-testnet_v0.1.zip
> cd mantis-1.0-daedalus-rc1
# run the wallet/node
> ./bin/mallet https://kevm-testnet.iohkdev.io:8546
> mallet> newAccount()
0xdce08ffc656b1526b07b7a63252b3296c39d3b21
> mallet> newAccount()
0x474786ff87f1289a4e4bf7ac2840078f6a4fc620
> mallet> selectAccount(senderAddress)
# get tokens here: https://testnet.iohkdev.io/goguen/faucet/
# or use this: curl -X POST -k https://kevm-testnet.iohkdev.io:8099/faucet?address=<senderAddress>
# send transaction
> sendTransaction(to = receiverAddress, gas = 5000000, gasPrice = 5000000000, value = 123456, data = "simple value transfer")
# check if transaction was successful
> mallet> selectAccount(receiverAddress)
> mallet> getBalance
123456
```

**Comment by mirkoAlic** [comment]
Disclaimer: Currently there is no support for `Cardano KEVM`. And regarding how to run Mantis, short answer; As any other JVM based application (Notice that now you can build Mantis by using nix if you want)
