### ISSUE TITLE
Non-interactive mode still expect tty

### ISSUE THREAD

**Issue by wang2bo2** [input-output-hk/mantis#489]
Doesn't this defeat the purpose of the non-interactive mode?

```
{ Error: Command failed: /mantis/bin/mallet "https://kevm-testnet.iohkdev.io:8546/" -c "help()"
Exception in thread "main" com.sun.jna.LastErrorException: [25] Not a tty
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:408)
	at com.sun.jna.Function.invoke(Function.java:354)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at com.sun.proxy.$Proxy0.tcgetattr(Unknown Source)
	at org.jline.terminal.impl.jna.linux.LinuxNativePty.getAttr(LinuxNativePty.java:64)
	at org.jline.terminal.impl.AbstractPosixTerminal.<init>(AbstractPosixTerminal.java:33)
	at org.jline.terminal.impl.PosixSysTerminal.<init>(PosixSysTerminal.java:37)
	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:234)
	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:149)
	at org.jline.terminal.TerminalBuilder.terminal(TerminalBuilder.java:46)
	at io.iohk.ethereum.mallet.main.Shell.<init>(Shell.scala:18)
	at io.iohk.ethereum.mallet.main.Mallet$.delayedEndpoint$io$iohk$ethereum$mallet$main$Mallet$1(Mallet.scala:20)
	at io.iohk.ethereum.mallet.main.Mallet$delayedInit$body.apply(Mallet.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at io.iohk.ethereum.mallet.main.Mallet$.main(Mallet.scala:13)
	at io.iohk.ethereum.App$.main(App.scala:28)
	at io.iohk.ethereum.App.main(App.scala)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/mantis/bin/mallet "https://kevm-testnet.iohkdev.io:8546/" -c "help()"' }
```

**Comment by mirkoAlic** [comment]
No longer support for `kevm-testnet` (not for now).
