### ISSUE TITLE
bin/mantis --> UDP server not running. Not sending ping message.

### ISSUE THREAD

**Issue by drandreaskrueger** [input-output-hk/mantis#505]
```
~/Downloads/ware/mantis-1.0-daedalus-rc1$ bin/mantis 

11:26:41 Slf4jLogger started
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'environment'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
	at io.iohk.ethereum.metrics.MetricsConfig$.apply(MetricsConfig.scala:38)
	at io.iohk.ethereum.metrics.MetricsClient$.configure(MetricsClient.scala:80)
	at io.iohk.ethereum.nodebuilder.BaseNode.startMetricsClient(StdNode.scala:55)
	at io.iohk.ethereum.nodebuilder.BaseNode.start(StdNode.scala:62)
	at io.iohk.ethereum.Mantis$.main(Mantis.scala:12)
	at io.iohk.ethereum.App$.main(App.scala:23)
	at io.iohk.ethereum.App.main(App.scala)

11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:26:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
11:27:51 UDP server not running. Not sending ping message.
```

**Comment by drandreaskrueger** [comment]
might be related to https://github.com/input-output-hk/mantis/issues/504 what about a manual?

**Comment by hellc** [comment]
Should be related with #469

**Comment by mirkoAlic** [comment]
No longer support for daedalus integration.
